export const UserData = [
    {
        Nombre: "Juan Sebastian",
        Parroquia: "San Juan",
        Decano: "Decano1",
        Zona: "Monterrey",
        Edad: "66",
        MMSE:true,
        SARCF:true,
        CFS:true,
        KATZ:true,
        ADGY:true,
        PR:true,
        VSG:true,
        SPPB:true,
    },
    {
        Nombre: "Juan Carlos",
        Parroquia: "San Agustin",
        Decano: "Decano2",
        Zona: "Monterrey",
        Edad: "70",
        MMSE:false,
        SARCF:true,
        CFS:false,
        KATZ:false,
        ADGY:false,
        PR:false,
        VSG:false,
        SPPB:false,
    },
    {
        Nombre: "Daniel  Lorenzen",
        Parroquia: "San Felipe",
        Decano: "Decano2",
        Zona: "Monterrey",
        Edad: "80",
        MMSE:false,
        SARCF:false,
        CFS:true,
        KATZ:false,
        ADGY:false,
        PR:false,
        VSG:false,
        SPPB:false,
    },
    {
        Nombre: "Memo Lopez",
        Parroquia: "San Juan",
        Decano: "Decano4",
        Zona: "Monterrey",
        Edad: "83",
        MMSE:false,
        SARCF:false,
        CFS:false,
        KATZ:true,
        ADGY:true,
        PR:false,
        VSG:false,
        SPPB:false,
    },
    {
        Nombre: "Marcelo Marquez",
        Parroquia: "San Felipe",
        Decano: "Decano2",
        Zona: "Monterrey",
        Edad: "63",
        MMSE:false,
        SARCF:false,
        CFS:false,
        KATZ:false,
        ADGY:true,
        PR:false,
        VSG:false,
        SPPB:false,
    },
    {
        Nombre: "Eduardo Gonzales",
        Parroquia: "San Juan",
        Decano: "Decano1",
        Zona: "Monterrey",
        Edad: "64",
        MMSE:false,
        SARCF:false,
        CFS:false,
        KATZ:false,
        ADGY:false,
        PR:true,
        VSG:true,
        SPPB:true,
    },
    {
        Nombre: "Eduardo Gonzalez",
        Parroquia: "San Miguel",
        Decano: "Decano7",
        Zona: "Guadalupe",
        Edad: "69",
        MMSE:false,
        SARCF:false,
        CFS:true,
        KATZ:true,
        ADGY:true,
        PR:false,
        VSG:true,
        SPPB:false,
    },
    {
        Nombre: "Lucas Lobos",
        Parroquia: "San Nicolas",
        Decano: "Decano5",
        Zona: "San Nicolas",
        Edad: "58",
        MMSE:true,
        SARCF:true,
        CFS:false,
        KATZ:true,
        ADGY:false,
        PR:false,
        VSG:false,
        SPPB:true,
    },
    {
        Nombre: "Juan Antonio",
        Parroquia: "San Juan",
        Decano: "Decano5",
        Zona: "Apodaca",
        Edad: "80",
        MMSE:false,
        SARCF:true,
        CFS:true,
        KATZ:false,
        ADGY:false,
        PR:true,
        VSG:true,
        SPPB:false,
    },
    {
        Nombre: "Justin Sebstian",
        Parroquia: "San Miguel",
        Decano: "Decano8",
        Zona: "Nuevo Laredo",
        Edad: "74",
        MMSE:true,
        SARCF:true,
        CFS:true,
        KATZ:true,
        ADGY:true,
        PR:true,
        VSG:true,
        SPPB:true,
    },
    {
        Nombre: "Leonardo Anibal",
        Parroquia: "San Franco",
        Decano: "Decano1",
        Zona: "Apodaca",
        Edad: "65",
        MMSE:false,
        SARCF:true,
        CFS:true,
        KATZ:false,
        ADGY:true,
        PR:false,
        VSG:true,
        SPPB:false,
    },
    
  ];
  
// MMSE:false,
// SARCF:false,
// CFS:false,
// KATZ:false,
// ADGY:false,
// PR:false,
// VSG:false,
// SPPB:false,

// MMSE:true,
// SARCF:true,
// CFS:true,
// KATZ:true,
// ADGY:true,
// PR:true,
// VSG:true,
// SPPB:true,